# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday20181016',
                'doc_host': 'https://mattgiguere.github.io',
                'git_url': 'https://github.com/mattgiguere/tidytuesday20181016',
                'lib_path': 'tidytuesday20181016'},
  'syms': {'tidytuesday20181016.core': {'tidytuesday20181016.core.foo': ('core.html#foo', 'tidytuesday20181016/core.py')}}}
